### ISSUE TITLE
Use both GGA and RMC

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/nmea_navsat_driver#1]
Reference: https://github.com/ros-drivers/nmea_gps_driver/issues/2

Current state of affairs is that the user must choose between RMC messages (you get track and speed, but no covariance), or GGA messages (covariance, but no track or speed). This sucks—the driver should be able to make a few assumptions and do the right thing.

**Comment by PaulBouchier** [comment]
@mikepurvis can you please clarify your statement that you're getting vel from RMC and fix + covariance from GGA. The current code uses either/or depending on ~use_RMC, not both.

**Comment by PaulBouchier** [comment]
Since it works well enough, and it's 2 years old so is apparently not critically broken, I suggest closing this issue. Someone can re-open or open a new issue if they really feel they want to implement the original proposal.

**Comment by mikepurvis** [comment]
Sounds good.
