### ISSUE TITLE
Release for ROS Noetic

### ISSUE THREAD

**Issue by evenator** [ros-drivers/nmea_navsat_driver#103]
Test this package in ROS Noetic (notably, this requires Python3) and release a new version to ROS Noetic.

**Comment by donkikos** [comment]
Hey @evenator any updates on this?

**Comment by evenator** [comment]
The package was released in Noetic, but there's a known issue with Python 3 (see #111, and potential fix in #112).

**Comment by donkikos** [comment]
Thanks for quick response. I was able to clone, compile and run nmea_navsat_driver with 3 changes in different files. I also got stuck for some time on the issue you mentioned and was not able to figure out what that check meant. Thanks for the links, at least it clears out what the if is meant to check. 

So is the package in the ubuntu repos? I was not able to install it with apt. It does not show here too - https://wiki.ros.org/nmea_navsat_driver

**Comment by evenator** [comment]
Looks like you're right. I could have sworn I released it for noetic. I'll test it today and bloom a release.

**Comment by evenator** [comment]
Release is pending ros/rosdistro#26721

**Comment by donkikos** [comment]
Great, thank you @evenator !
