### ISSUE TITLE
Hemisphere v103 heading support

### ISSUE THREAD

**Issue by l0g1x** [ros-drivers/nmea_navsat_driver#11]
I know the navsat driver publishes a fix topic which has lat, long, alt, but my gps (hemisphere v103) contains two antennas allowing for a heading nmea string to be published as well. I was wondering if it could be possible to add a part in the fix message that also sends heading in radians. I have pretty much already written the code for it, but right now i have it publishing on its own topic /heading. I need it so that the lat, long, alt, and heading are all in one fix message, so when i receive a call back in the gps_common utm_odometry_node, i can create the odometry at the same time with the same timestamp. Would this be possible? I can fork and pull request if need be. 
P.S. the v103 can be added to the verified gps list because we have been using it for about 6months now with no problems.

**Comment by mr337** [comment]
I know this has been open a while but any updates? I got a H321 coming in that provides heading and if not will attempt to open a PR going with the proposal of publishing a `/heading` topic.

**Comment by mr337** [comment]
https://github.com/ros-drivers/nmea_navsat_driver/pull/25, this uses the NMEA GPHDT and not the binary format, so should work with other receivers than the v301 and H321

**Comment by evenator** [comment]
Issue Summary:

- Some GNSS receivers output heading, but `sensor_msgs/NavSatFix` has no field for it.
- The fix proposed by @ericperko and @jack-oquin is to also publish a `geometry_msgs/QuaternionStamped` containing this heading (if available) with the same timestamp as the corresponding `sensor_msgs/NavSatFix` message.
- @mr337 has implemented this fix in PR #25, but it hasn't been merged yet.

**Comment by evenator** [comment]
Closing this as fixed by #25.
