### ISSUE TITLE
cannot get this to work

### ISSUE THREAD

**Issue by skysingh** [ros-drivers/nmea_navsat_driver#126]
I install using git clone in jetson nano. into catkin_ws/src folder. The ran catkin_make. Seemed to build file.

But when I run the sample line:

$ rosrun nmea_navsat_driver nmea_serial_driver _port:=/dev/ttyUSB0 _baud:=115200

I get:

Illegal instruction (core dumped)
What have I done wrong? Thanks.

**Comment by evenator** [comment]
This appears to be a problem specific to the Python installation on your Jetson Nano. See the discussion here https://stackoverflow.com/questions/65631801/illegal-instructioncore-dumped-error-on-jetson-nano
