### ISSUE TITLE
how to remove leading / from frame_id

### ISSUE THREAD

**Issue by elgarbe** [ros-drivers/nmea_navsat_driver#128]
I'm using robot localization package and it doesn't like the "/" on the frame id. I've read some stuff on the closed issues, but I'm not sure how to correct this. I've installed from binaries on kinetic and it uses the "/"
Do I need to install from source? which branch is used for kinetic and have this issue solved? 

Thank

**Comment by evenator** [comment]
There is no way to configure the driver to not use the leading `/` prefix. If you wish to install from source, ROS kinetic uses the `kinet-devel` branch, and you can edit the static method `get_frame_id()` to remove the prefix https://github.com/ros-drivers/nmea_navsat_driver/blob/42310d4b3894a45af0efd921582791ab8a17d53f/src/libnmea_navsat_driver/driver.py#L199-L211
