### ISSUE TITLE
ROS2 Foxy Status?

### ISSUE THREAD

**Issue by mr337** [ros-drivers/nmea_navsat_driver#131]
We are making the transition from ROS1 to ROS2. It looks like there was some work getting this package compatible with ROS2. https://github.com/ros-drivers/nmea_navsat_driver/issues/61

Checking [ROS packages](https://index.ros.org/p/nmea_navsat_driver/github-ros-drivers-nmea_navsat_driver/#noetic) and apt not seeing a Foxy version. :(

Does anyone know the blocker to updating this to support Foxy? Also happy to lend a hand as part of the upgrade process.

**Comment by maxpolzin** [comment]
What needs to be done to officially release the driver fro ROS2? I am happy to put some effort into this.

**Comment by evenator** [comment]
I don't know how well the ROS 2 branch works (or doesn't work) in Foxy. The first step would be for someone to install the package from source in foxy and see what needs to be updated or fixed.

**Comment by mr-church** [comment]
I am trying to get this driver working in Foxy with a Garmin 18x sensor. Any updates on this issue that I should take note of?

**Comment by evenator** [comment]
Closing this as Foxy is EOL as of June 20, 2023
