### ISSUE TITLE
I want to install from source,when I run catkin_make,this occured "Could not find the required component 'catkin_virtualenv'.", how can I solve this problem ?

### ISSUE THREAD

**Issue by fengyikawhi** [ros-drivers/nmea_navsat_driver#140]

**Comment by evenator** [comment]
Can you provide some more info, such as your ROS version, OS version, and the full process you've attempted to follow to install from source?

**Comment by fengyikawhi** [comment]
Thanks for your apply, Ubuntu20.04, ROS noetic, 
process:
 mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src
git clone https://github.com/ros-drivers/nmea_navsat_driver.git
cd ~/catkin_ws
catkin_make

**Comment by evenator** [comment]
Ensure you have installed and initialized [rosdep](http://wiki.ros.org/rosdep), then use it to install the dependencies:
```
cd ~/catkin_ws/src
rosdep install --from-paths nmea_navsat_driver --ignore-src
```

**Comment by fengyikawhi** [comment]
> Ensure you have installed and initialized [rosdep](http://wiki.ros.org/rosdep), then use it to install the dependencies:
> 
> ```
> cd ~/catkin_ws/src
> rosdep install --from-paths nmea_navsat_driver --ignore-src
> ```

Excellent! I solved the problem, thanks a lot!
