### ISSUE TITLE
I want to modify part of the code to decode my own devices, which version of python should I use? 2.7 or 3.x?

### ISSUE THREAD

**Issue by fengyikawhi** [ros-drivers/nmea_navsat_driver#142]

**Comment by mr337** [comment]
It depends on the target ROS distro you are using. Pre Noetic, python2.7, Noetic or newer 3.X.

**Comment by evenator** [comment]
@mr337 is correct. See [REP 3](https://www.ros.org/reps/rep-0003.html) for ROS 1 platform info and [REP 2000](https://www.ros.org/reps/rep-2000.html) for ROS 2 platform info.
