### ISSUE TITLE
New to GPS

### ISSUE THREAD

**Issue by YXGuan** [ros-drivers/nmea_navsat_driver#151]
Hi there,

A newbie to GPS here, I have a few questions:

1. What GPS modules (compatible with nmea_navsat_driver) would you recommend?
2. How would the GPS package interact with move_base_goal and other navigation packages?

I appreciate anything (tutorials/vidoes/links) you could share : )

**Comment by evenator** [comment]
Hi @YXGuan. Please only use the issue tracker to report bugs and feature requests with this package. For general questions, please use answers.ros.org.
