### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by aristow1** [ros-drivers/nmea_navsat_driver#155]
Hi im using Ubuntu 18.04 and ros melodic. I tried launching the "roslaunch nmea_navsat_driver nmea_serial_driver.launch" file and i get this error : ModuleNotFoundError: No module named 'serial'.
i tried installing serial with : sudo apt-get install python-serial and with pip install serial and i have everything installed : Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-serial is already the newest version (3.4-2).
The following package was automatically installed and is no longer required:
  linux-hwe-5.4-headers-5.4.0-84
Use 'sudo apt autoremove' to remove it.
 and i still get the same error. i dont know how to solve it. any idea ?

**Comment by Joy-Zhang-0303** [comment]
Hello, I'm also using this package. Everything is also. My Python is 2.7 . Could you show the Python installed path ?

**Comment by aristow1** [comment]
HI my python installation path is /usr/bin/python. im also using python 2.7. i also use melodic-devel

**Comment by aristow1** [comment]
how do i check the name of the serial port the gps is connected to. im using a COM port ?

**Comment by aristow1** [comment]
i will try this tomorrow and let you know if it works. thank you :)

**Comment by aristow1** [comment]
i was using python 3 to build the package and that was the Problem. after using python2.7 to build + the solution of @evenator the Problem was solved. Thanks !
