### ISSUE TITLE
Received a sentence with an invalid checksum 

### ISSUE THREAD

**Issue by ishaanamahajan** [ros-drivers/nmea_navsat_driver#166]
![Screenshot from 2023-04-04 17-08-21](https://user-images.githubusercontent.com/73236968/229935897-e773b3ef-a095-4e3c-8a00-a30f5fcb5e89.png)

I have made sure the baud rates of the device and the one in nmea_serial_driver.py are the same (115200). I am using a novatel PwrPak 7. Any help would be appreciated!

**Comment by TheodorPatrickZ** [comment]
Hey have you found a solution?
I had the same issue Today.

**Comment by praajnabaragur** [comment]
I'm getting this too, any solution?

**Comment by evenator** [comment]
Judging from the error messages, you seem to be getting _empty_ messages. Without more information, I don't think anyone can help you debug this further, but I don't see anything that indicates a bug in the driver software.
