### ISSUE TITLE
ROS 2 Humble release

### ISSUE THREAD

**Issue by roni-kreinin** [ros-drivers/nmea_navsat_driver#167]
Can this package be released to Humble? I noticed it is only released on Iron and Rolling.

**Comment by tonybaltovski** [comment]
@cottsay can you release this for Humble as it was released for Rolling and Iron already?

**Comment by cottsay** [comment]
> can you release this for Humble as it was released for Rolling and Iron already?

That's completely up to the maintainer of the package, @evenator, who released the package for Rolling.

**Comment by tonybaltovski** [comment]
@evenator could you please take a look at this soon?

**Comment by gmsanchez** [comment]
A Humble package would be great. Is there any way we could help?

**Comment by evenator** [comment]
Working on a Humble release right now, as well as an update to Rolling.

**Comment by evenator** [comment]
Version 2.0.1 is now released for Humble, Iron, and Rolling.
