### ISSUE TITLE
Ros error: The 'sentence' field must be of type 'str'

### ISSUE THREAD

**Issue by FletcherFT** [ros-drivers/nmea_navsat_driver#172]
ROS2 Humble

When running nmea_topic_serial_reader, receive this error. Think it is [this](https://github.com/ros-drivers/nmea_navsat_driver/blob/861323c83c04ca02454187c85528ddca9a7ef94d/src/libnmea_navsat_driver/nodes/nmea_topic_serial_reader.py#L63)

Should be data.decode("ascii")

**Comment by evenator** [comment]
Thank you for finding this and for the pull request!
