### ISSUE TITLE
documentation:  missing example

### ISSUE THREAD

**Issue by kylerlaird** [ros-drivers/nmea_navsat_driver#23]
http://wiki.ros.org/nmea_navsat_driver

Sample Usage

To get up and running quickly, you can use the following command to start outputting your GPS data onto ROS topics. This assumes your GPS is outputting GGA NMEA sentences, is connected to /dev/ttyUSB0 and is communicating at 38400 baud.

[Example only shows for hydro and indigo.]

**Comment by tonybaltovski** [comment]
Updated, thanks.

**Comment by sonyccd** [comment]
Is this open?

**Comment by tonybaltovski** [comment]
The changes were applied.

**Comment by TSRyan** [comment]
The "melodic" tab does not display the example command.
