### ISSUE TITLE
Multiple GPS Support Question

### ISSUE THREAD

**Issue by SupermanPrime01** [ros-drivers/nmea_navsat_driver#34]
Hello,

I've been using this driver and it's pretty cool but I wanted to use 2 GPS units with this driver. The problem I have is when I run one driver, the other GPS driver turns off. Is there a way to have 2 GPS nodes and have them publish on their own separate topics? For example, nmea_node1 publishes to topic fix1 and nmea_node2 publishes to topic fix2. How would I go about in order to achieve this?

Thank you

**Comment by jack-oquin** [comment]
This is a basic ROS question, suitable for http://answers.ros.org. Please ask it there.

For a start, please look up the ROS methods for renaming nodes and remapping topic names. The basic tutorials are a good place to begin.
