### ISSUE TITLE
Dose it support raspignss nmea meassge?

### ISSUE THREAD

**Issue by jongchul** [ros-drivers/nmea_navsat_driver#37]
Hi. 

  I've installed setup raspignss module that uses NV08C. (http://drfasching.com/products/discontinued/raspignss-cook/installation.html)        

 Attached file is nmea message after sending 'nmeaparsing' command on the host. Can nmea_navsat_driver be used in raspignss module? [
![nmeaparse](https://user-images.githubusercontent.com/6112016/32664023-47b5fb2a-c673-11e7-9d14-02986242fc92.jpg)
](url)

**Comment by evenator** [comment]
If your device outputs the standard NMEA sentences [GPGGA](http://aprs.gids.nl/nmea/#gga) or [GPRMC](http://aprs.gids.nl/nmea/#rmc), you can use it with this driver.
