### ISSUE TITLE
change the publishing rate

### ISSUE THREAD

**Issue by wawachen** [ros-drivers/nmea_navsat_driver#42]
Is there any possibility I can change the publishing rate of /fix?
I have noticed the frequency is approximately 1 HZ, how can I make it faster?

**Comment by wawachen** [comment]
In nmea_serial_driver node, I add rospy.Rate(5)  BUT the frequency of the publishing topic /fix is always 1hz.I do not know how to change the rate.

**Comment by evenator** [comment]
The problem is probably that your device is only outputting NMEA sentences at 1 Hz. Depending on the device, you may be able to change the rate. Consult the documentation from the manufacturer of your device.
