### ISSUE TITLE
Clean termination of nodes

### ISSUE THREAD

**Issue by akashp1997** [ros-drivers/nmea_navsat_driver#47]
I think that in both the Node scripts **nmea_serial_driver** and **nmea_serial_topic_driver**, there is a need for the catching of the exception caused when there is a serial error produced as there is a need to provide any errors caused to both the screen and the logging files of ROS.

**Comment by evenator** [comment]
Hi @akashp1997. Thanks for pointing this out.

It looks like @shahvi reported this problem (or a similar one) in #51 as well. I don't have a lot of time to maintain this package, but I'd welcome a PR from anyone who has time to fix it.
