### ISSUE TITLE
Date (dd/mm/yy) is ignored when using RMC sentences

### ISSUE THREAD

**Issue by ericperko** [ros-drivers/nmea_navsat_driver#6]
Unlike GGA, RMC sentences do include an absolute date stamp. When using RMC sentences, this data should be used when computing the timestamp instead of simply taking the current clock time and adjusting the hours, minutes and seconds fields as is done with GGA sentences.

**Comment by PaulBouchier** [comment]
Please clarify my understanding of the fault description above. It sounds like it says GGA & RMC are used when computing the timestamp for the fix, but they aren't put in the NavSatFix message timestamp, they are emitted as TimeReference on the time_reference topic. Is that what's meant by the above, and the request is to use date from RMC in the time_reference?

TimeReference is incorrectly built currently - the code assumes utc_time is in seconds, but it is actually hhmmss.ss.

I guess TimeReference enables syncing system wallclock time to GPS UTC time? I guess it would enable a NavSatFix to be tied back to UTC time, if that were needed for some reason. Is that correct?

**Comment by evenator** [comment]
Fixed by #79
