### ISSUE TITLE
ROS 2 Drivers for OXTS GPS/IMU products

### ISSUE THREAD

**Issue by NEUUGV** [ros-drivers/nmea_navsat_driver#81]
Hello ROS developers! 
I would like make use of an OXTS GPS/IMU product (i.e., a RT2000 system component) under ROS 2 Dashing Diademata. Therefore, I wonder if there exist ROS 2 Dashing Diademata drivers for OXTS GPS/IMU products.

**Comment by evenator** [comment]
I'm not aware of any. If the device produces NMEA output, this driver should work for the that part, but this driver has no IMU support. The ROS 2 branch is experimental--check out the `ros_2` branch--and it isn't yet updated for Dashing (see #80)
