### ISSUE TITLE
heading axis orientation

### ISSUE THREAD

**Issue by mbudris** [ros-drivers/nmea_navsat_driver#83]
From what I understand nmea HDT sentences provide yaw angle in NED coordinate frame, and subsequently the driver follows to provide quaternions in the same notation.

What would be the best practice to transform to ENU to have correct input for robot_localization and similar?

**Comment by evenator** [comment]
The driver provides the yaw angle and velocity in the same frame provided by the receiver, which is typically NED. However, the driver avoids making this assumption and publishes the yaw and velocity _as received from the device_. The most common practice is to use an intermediate frame and transform coordinates with TF as described in [REP-103](https://www.ros.org/reps/rep-0103.html):

> For outdoor systems where it is desirable to work under the north east down [6] (NED) convention, define an appropriately transformed secondary frame with the "_ned" suffix

This is consistent with practices for other sensors. For example, an IMU driver would publish in the ego frame of the IMU, and a transform would be necessary to put the measurements in the ego frame of the robot.
