### ISSUE TITLE
What reference frame is used for the velocity?

### ISSUE THREAD

**Issue by BillThePlatypus** [ros-drivers/nmea_navsat_driver#84]
Velocity is reported through the linear field of a TwistStamped. What reference frame is this using? NED, ENU, ECEF? The documentation doesn't seem to indicate, and this is essential to use the data correctly.

**Comment by evenator** [comment]
The velocity contains x and y components, which are calculated from the [NMEA RMC](https://www.gpsinformation.org/dale/nmea.htm#RMC) sentence's `speed` and `track angle` fields. The reference frame of the `track angle` is typically NED, but the driver takes it directly from the GPS receiver, so it depends what your receiver is publishing.
