### ISSUE TITLE
"Received a Sentence with Invalid Checksum sentence was : " "

### ISSUE THREAD

**Issue by jimmywklee** [ros-drivers/nmea_navsat_driver#97]
I have similar issue as per  "sdey76 opened this issue on Feb 2
 " https://github.com/ros-drivers/nmea_navsat_driver/issues/94#issue-558656238

I have a win7 notebook and running virtualbox/ubuntu 14.04, my GPS model : ublox NEO-6M-0-001 (USB version)

I verified by installing putty on both win7 and ubuntu, the putty on win7 can get GPS data but not  virtualbox/ubuntu 14.04, 
 
I believe my problem was due to same of the O.S. not releasing resource properly

I did the follow steps 

-shutdown all the O.S. inside virtualbox (send the shutdown signal,  not power off the machine) 
-remove usb filter in virtualbox and  close virtualbox
-In window 7 device manager , I  "enable" then "disable" then "enable" the usb com
-open virtual and add the usb-com port back
-start ubuntu and putty, if the GPS data appeared then the ROS issue gone.

I did face similar issues on usb-cam and other usb-com device via virtualbox/ubuntu.  The issue will be gone if the resource is released.

**Comment by evenator** [comment]
> I believe my problem was due to same of the O.S. not releasing resource properly

It sounds to be like this is a problem with your operating system or virtual machine, not an issue with this software package.
